default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: the_app_development
  username: <%= Rails.application.secrets[:db_user] %>
  password: <%= Rails.application.secrets[:db_password] %>

development:
  <<: *default
  database: the_app_test
  username: <%= Rails.application.secrets[:db_user] %>
  password: <%= Rails.application.secrets[:db_password] %>
