# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf75221023397316e0ba90f36d463ffa0ef08aa185dba4d69de679f66df9d451aa8387dabe4756fed4551dbb081a27d6a3bf8dfd03b6bd8ba7cd5647106c8dc
  db_user: root
  db_password: root

test:
  secret_key_base: 13125c4ac42f46b67e4d9f3e3c59521fcd1d0b9ad1251cc10e01da3a928d105df54bd7a90cf10813f8e45995e3855e058db98787be2537630381eca5e287e1d1
  db_user: root
  db_password: root

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
